custom:
  path:
    resource: file:///D:/Spring projects/SpringBoot LocalBatter/src/main/downloads/
    upload: /upload/**
    download: D:\Spring projects\SpringBoot LocalBatter\src\main\downloads\


server:
  port: 8000
  servlet:
    context-path: /
    encoding:
      charset: UTF-8
      enabled: true
      force: true
    
spring:
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp
  output:
    ansi:
      enabled: always
  handlerbars:
    suffix: .jsp
  devtools:
    restart:
      enabled: true

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3307/localbatterdb?serverTimezone=Asia/Seoul
    username: root
    password: 110731
    
  session:
    store-type: redis
  redis:
    timeout: 6000
    host: localhost
    port: 6379
    flush-mode: on-save
    namespace: spring:session

  jpa:
    open-in-view: true
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      use-new-id-generator-mappings: false
    show-sql: false 
    properties:
      hibernate.format_sql: true 

  jackson:
    serialization:
      fail-on-empty-beans: false